on:
  schedule:
    - cron: '0 9 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: node-v${{ matrix.node-version }}-deps-${{ hashFiles('./yarn.lock') }}
      - name: Yarn Install
        run: |
          yarn install
      - name: Update sites
        run: |
          yarn run do
      - name: git setting
        run: |
          git config --local user.email "aaaiiiuuu35@gmail.com"
          git config --local user.name "su-u"
      - name: Commit files
        run: |
          git add .
          git commit -m "Update: sites" -a
          git push origin main